[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    ; Bluepad32 for PS4/PS5 controller over Bluetooth
    ricardoquesada/Bluepad32 @ ^3.10.1
    ; High performance hardware quadrature encoders
    madhephaestus/ESP32Encoder @ ^0.11.2

build_flags = 
    ; Odkomentuj, pokud používáš Arduino knihovny pro Bluepad32 s USB Hostem, 
    ; ale u DevKitC většinou stačí základní flag
    -D CORE_DEBUG_LEVEL=3
